name: "Deploy master to scalingo (prod/staging)"

on:
  push:
    branches:
      - master

jobs:
  deploy-staging:
    uses: gip-inclusion/reusable-github-actions/.github/workflows/deploy-to-scalingo-from-github-targz.yml@main
    with:
      appName: ${{ vars.STAGING_APP_NAME }}
      region: ${{ vars.STAGING_REGION }}
      targzUrl: ${{ vars.TARGZ_URL }}
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}
  deploy:
    uses: gip-inclusion/reusable-github-actions/.github/workflows/deploy-to-scalingo-from-github-targz.yml@main
    with:
      appName: ${{ vars.APP_NAME }}
      region: ${{ vars.REGION }}
      targzUrl: ${{ vars.TARGZ_URL }}
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}